import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { AreaMaterialStock, Group, Material } from '../../core/models/models';
import { ModalComponent } from '../../shared/components/modal/modal.component';
import { IconsModule } from '../../shared/icons/icons.module';

@Component({ selector: 'app-categories', standalone: true, imports: [CommonModule, FormsModule, ModalComponent, IconsModule], template: `
<div class="space-y-6"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 class="text-2xl font-bold tracking-tight text-slate-900">Áreas / Zonas y Materiales</h2><p class="text-sm text-slate-500 mt-0.5">Un catálogo único de materiales, distribuido por área.</p></div><div class="flex gap-3"><button (click)="openAreaModal()" class="btn-outline"><lucide-icon name="plus" [size]="16"></lucide-icon> Nueva Área / Zona</button><button (click)="openStockModal()" class="btn-primary"><lucide-icon name="plus" [size]="16"></lucide-icon> Registrar existencias</button></div></div>
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="card-smp p-5 space-y-3"><div class="flex justify-between border-b pb-3"><h3 class="font-bold flex gap-2"><lucide-icon name="folder" [size]="17"></lucide-icon> Áreas / Zonas</h3><span class="text-xs bg-slate-100 px-2 py-0.5 rounded-full">{{ groups().length }}</span></div><button (click)="selectedGroupId.set(null)" [ngClass]="selectedGroupId() === null ? 'bg-primary text-white' : 'bg-slate-50'" class="w-full text-left p-3 rounded-xl text-sm font-semibold">Todas las áreas / zonas</button><button *ngFor="let group of groups()" (click)="selectedGroupId.set(group.id)" [ngClass]="selectedGroupId() === group.id ? 'bg-primary text-white' : 'bg-slate-50 hover:bg-slate-100'" class="w-full text-left p-3 rounded-xl text-sm font-semibold">{{ group.name }}</button></div>
<div class="lg:col-span-2 card-smp p-5"><div class="border-b pb-3 mb-3"><h3 class="font-bold">Existencias por área</h3><p class="text-xs text-slate-400 mt-1">{{ filteredStocks().length }} registros</p></div><div *ngIf="!filteredStocks().length" class="py-12 text-center text-sm text-slate-400">No hay existencias para este filtro.</div><div *ngIf="filteredStocks().length" class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600 text-xs"><tr><th class="p-3">Material</th><th class="p-3">Área / Zona</th><th class="p-3">Cantidad</th><th class="p-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-slate-100"><tr *ngFor="let stock of filteredStocks()"><td class="p-3 font-bold">{{ stock.material?.name }}</td><td class="p-3"><span class="px-2 py-1 bg-blue-50 text-blue-700 rounded-full text-xs">{{ stock.group?.name }}</span></td><td class="p-3 font-bold text-primary">{{ stock.quantity }}</td><td class="p-3 text-right"><button (click)="openStockModal(stock)" class="text-primary font-semibold hover:underline">Editar cantidad</button></td></tr></tbody></table></div></div></div>
<app-modal [isOpen]="areaModalOpen()" title="Nueva Área / Zona" maxWidth="max-w-md" (close)="areaModalOpen.set(false)"><div body class="space-y-3"><label class="block text-xs font-semibold">Nombre *</label><input [(ngModel)]="areaName" class="input-smp" placeholder="Ej: Salón 1, Biblioteca" /></div><div footer><button class="btn-outline" (click)="areaModalOpen.set(false)">Cancelar</button><button class="btn-primary" [disabled]="!areaName || saving()" (click)="saveArea()">Guardar</button></div></app-modal>
<app-modal [isOpen]="stockModalOpen()" [title]="editingStock() ? 'Editar cantidad' : 'Registrar existencias'" maxWidth="max-w-md" (close)="closeStockModal()"><div body class="space-y-4"><div><label class="block text-xs font-semibold mb-1">Área / Zona *</label><select [(ngModel)]="stockForm.groupId" [disabled]="!!editingStock()" class="select-smp"><option [ngValue]="null" disabled>Selecciona un área</option><option *ngFor="let group of groups()" [ngValue]="group.id">{{ group.name }}</option></select></div><div *ngIf="!editingStock()"><label class="block text-xs font-semibold mb-1">Material *</label><select [(ngModel)]="stockForm.materialId" class="select-smp"><option [ngValue]="null" disabled>Selecciona un material existente</option><option *ngFor="let material of materials()" [ngValue]="material.id">{{ material.name }}</option></select><div class="flex items-center gap-2 my-3 text-xs text-slate-400"><span class="flex-1 border-t"></span>o crear uno nuevo<span class="flex-1 border-t"></span></div><input [(ngModel)]="newMaterialName" class="input-smp" placeholder="Ej: Cargadores" /></div><div *ngIf="editingStock()"><label class="block text-xs font-semibold mb-1">Material</label><p class="input-smp bg-slate-50">{{ editingStock()?.material?.name }}</p></div><div><label class="block text-xs font-semibold mb-1">{{ editingStock() ? 'Cantidad total en esta área' : 'Cantidad a añadir' }} *</label><input type="number" min="0" [(ngModel)]="stockForm.quantity" class="input-smp" /></div></div><div footer><button class="btn-outline" (click)="closeStockModal()">Cancelar</button><button class="btn-primary" [disabled]="saving() || !stockForm.groupId || (!stockForm.materialId && !newMaterialName) || stockForm.quantity < 0" (click)="saveStock()">Guardar</button></div></app-modal></div>` })
export class CategoriesComponent implements OnInit {
  groups = signal<Group[]>([]); materials = signal<Material[]>([]); stocks = signal<AreaMaterialStock[]>([]); selectedGroupId = signal<number | null>(null); saving = signal(false); areaModalOpen = signal(false); stockModalOpen = signal(false); editingStock = signal<AreaMaterialStock | null>(null); areaName = ''; newMaterialName = ''; stockForm = { groupId: null as number | null, materialId: null as number | null, quantity: 1 };
  filteredStocks = computed(() => this.stocks().filter((stock) => this.selectedGroupId() === null || stock.groupId === this.selectedGroupId()));
  constructor(private api: ApiService, private toast: ToastService) {}
  ngOnInit() { this.load(); }
  load() { this.api.get<Group[]>('/groups').subscribe({ next: g => this.groups.set(g) }); this.api.get<Material[]>('/materials').subscribe({ next: m => this.materials.set(m) }); this.api.get<AreaMaterialStock[]>('/materials/stocks').subscribe({ next: s => this.stocks.set(s), error: () => this.toast.error('No se pudieron cargar los materiales.') }); }
  openAreaModal() { this.areaName = ''; this.areaModalOpen.set(true); }
  saveArea() { this.saving.set(true); this.api.post('/groups', { name: this.areaName.trim(), description: '' }).subscribe({ next: () => { this.saving.set(false); this.areaModalOpen.set(false); this.load(); }, error: e => { this.toast.error(e?.error?.message || 'No se pudo crear el área.'); this.saving.set(false); } }); }
  openStockModal(stock?: AreaMaterialStock) { this.editingStock.set(stock || null); this.newMaterialName = ''; this.stockForm = stock ? { groupId: stock.groupId, materialId: stock.materialId, quantity: stock.quantity } : { groupId: this.selectedGroupId() || this.groups()[0]?.id || null, materialId: null, quantity: 1 }; this.stockModalOpen.set(true); }
  closeStockModal() { this.stockModalOpen.set(false); this.editingStock.set(null); }
  saveStock() { const edit = this.editingStock(); this.saving.set(true); if (edit) { this.api.put(`/materials/stocks/${edit.id}`, { quantity: Number(this.stockForm.quantity) }).subscribe({ next: () => this.finish('Cantidad actualizada.'), error: e => this.fail(e) }); return; } if (this.newMaterialName.trim()) { this.api.post<Material>('/materials', { name: this.newMaterialName }).subscribe({ next: m => { this.stockForm.materialId = m.id; this.addStock(); }, error: e => this.fail(e) }); } else this.addStock(); }
  private addStock() { this.api.post('/materials/stocks', { groupId: this.stockForm.groupId, materialId: this.stockForm.materialId, quantity: Number(this.stockForm.quantity) }).subscribe({ next: () => this.finish('Existencias registradas.'), error: e => this.fail(e) }); }
  private finish(message: string) { this.toast.success(message); this.saving.set(false); this.closeStockModal(); this.load(); }
  private fail(error: any) { this.toast.error(error?.error?.message || 'No se pudo guardar.'); this.saving.set(false); }
}
