import { Component, OnInit, signal, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { ApiService } from '../../core/services/api.service';
import { ToastService } from '../../core/services/toast.service';
import { AreaMaterialStock, Computer, Group, Material } from '../../core/models/models';
import { ModalComponent } from '../../shared/components/modal/modal.component';
import { IconsModule } from '../../shared/icons/icons.module';

interface AreaInventoryRow {
  key: string;
  groupId: number;
  name: string;
  groupName: string;
  quantity: number;
  stock?: AreaMaterialStock;
}

@Component({ selector: 'app-categories', standalone: true, imports: [CommonModule, FormsModule, ModalComponent, IconsModule], template: `
<div class="space-y-6"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h2 class="text-2xl font-bold tracking-tight text-slate-900">Áreas / Zonas y Materiales</h2><p class="text-sm text-slate-500 mt-0.5">Un catálogo único de materiales, distribuido por área.</p></div><div class="flex gap-3"><button (click)="openAreaModal()" class="btn-outline"><lucide-icon name="plus" [size]="16"></lucide-icon> Nueva Área / Zona</button><button (click)="openStockModal()" class="btn-primary"><lucide-icon name="plus" [size]="16"></lucide-icon> Registrar existencias</button></div></div>
<div class="grid grid-cols-1 lg:grid-cols-3 gap-6"><div class="card-smp p-5 space-y-3"><div class="flex justify-between border-b pb-3"><h3 class="font-bold flex gap-2"><lucide-icon name="folder" [size]="17"></lucide-icon> Áreas / Zonas</h3><span class="text-xs bg-slate-100 px-2 py-0.5 rounded-full">{{ groups().length }}</span></div><button (click)="selectGroup(null)" [ngClass]="selectedGroupId() === null ? 'bg-primary text-white' : 'bg-slate-50'" class="w-full text-left p-3 rounded-xl text-sm font-semibold">Todas las áreas / zonas</button><div *ngFor="let group of groups()" class="flex items-center gap-1 rounded-xl" [ngClass]="selectedGroupId() === group.id ? 'bg-primary text-white' : 'bg-slate-50 hover:bg-slate-100'"><button (click)="selectGroup(group.id)" class="min-w-0 flex-1 p-3 text-left text-sm font-semibold truncate">{{ group.name }}</button><button (click)="openAreaModal(group)" class="p-2 mr-1 rounded-lg hover:bg-white/20 focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2" [attr.aria-label]="'Editar área ' + group.name" title="Editar área"><lucide-icon name="pencil" [size]="15"></lucide-icon></button></div></div>
<div class="lg:col-span-2 card-smp p-5"><div class="border-b pb-3 mb-3"><h3 class="font-bold">Existencias por área</h3><p class="text-xs text-slate-400 mt-1">{{ filteredRows().length }} registros</p></div><div *ngIf="!filteredRows().length" class="py-12 text-center text-sm text-slate-400">No hay existencias para este filtro.</div><div *ngIf="filteredRows().length" class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="bg-slate-50 text-slate-600 text-xs"><tr><th class="p-3">Material</th><th class="p-3">Área / Zona</th><th class="p-3">Cantidad</th><th class="p-3 text-right">Acciones</th></tr></thead><tbody class="divide-y divide-slate-100"><tr *ngFor="let row of pagedRows()"><td class="p-3 font-bold">{{ row.name }}</td><td class="p-3"><span class="px-2 py-1 bg-blue-50 text-blue-700 rounded-full text-xs">{{ row.groupName }}</span></td><td class="p-3 font-bold text-primary">{{ row.quantity }}</td><td class="p-3 text-right whitespace-nowrap"><ng-container *ngIf="row.stock; else computerActions"><button type="button" (click)="openStockModal(row.stock)" class="p-1.5 mr-1 text-primary hover:bg-primary/10 rounded-lg transition-colors inline-flex items-center justify-center" [attr.aria-label]="'Editar cantidad de ' + row.name" title="Editar cantidad"><lucide-icon name="pencil" [size]="15"></lucide-icon></button><button type="button" (click)="confirmDeleteStock(row.stock)" class="p-1.5 text-rose-600 hover:bg-rose-50 rounded-lg transition-colors inline-flex items-center justify-center" [attr.aria-label]="'Eliminar ' + row.name" title="Eliminar material"><lucide-icon name="trash-2" [size]="15"></lucide-icon></button></ng-container><ng-template #computerActions><span class="text-xs text-slate-400">Gestionar en Cómputo</span></ng-template></td></tr></tbody></table></div><div *ngIf="filteredRows().length > pageSize" class="flex items-center justify-between border-t border-slate-100 pt-4 mt-3 text-xs text-slate-500"><span>Página {{ stockPage }} de {{ stockPageCount() }}</span><div class="flex gap-2"><button class="btn-outline py-1.5" [disabled]="stockPage === 1" (click)="stockPage = stockPage - 1">Anterior</button><button class="btn-outline py-1.5" [disabled]="stockPage >= stockPageCount()" (click)="stockPage = stockPage + 1">Siguiente</button></div></div></div></div>
<app-modal [isOpen]="areaModalOpen()" [title]="editingArea() ? 'Editar Área / Zona' : 'Nueva Área / Zona'" maxWidth="max-w-md" (close)="areaModalOpen.set(false)"><div body class="space-y-3"><label class="block text-xs font-semibold">Nombre *</label><input [(ngModel)]="areaName" class="input-smp" placeholder="Ej: Salón 1, Biblioteca" /><label class="block text-xs font-semibold">Descripción</label><textarea [(ngModel)]="areaDescription" class="input-smp" rows="2"></textarea></div><div footer class="flex w-full items-center gap-2"><button *ngIf="editingArea()" type="button" class="btn-danger mr-auto" [disabled]="saving()" (click)="deleteAreaModalOpen.set(true)"><lucide-icon name="trash-2" [size]="16"></lucide-icon> Eliminar área</button><button type="button" class="btn-outline" (click)="areaModalOpen.set(false)">Cancelar</button><button type="button" class="btn-primary" [disabled]="!areaName.trim() || saving()" (click)="saveArea()">Guardar</button></div></app-modal>
<app-modal [isOpen]="deleteAreaModalOpen()" title="Eliminar Área / Zona" maxWidth="max-w-md" (close)="deleteAreaModalOpen.set(false)"><div body class="text-sm text-slate-600">¿Seguro que deseas eliminar <strong>{{ editingArea()?.name }}</strong>? Esta acción no se puede deshacer. Si tiene materiales o laptops asociados, no se podrá eliminar.</div><div footer><button type="button" class="btn-outline" [disabled]="saving()" (click)="deleteAreaModalOpen.set(false)">Cancelar</button><button type="button" class="btn-danger" [disabled]="saving()" (click)="deleteArea()">Eliminar</button></div></app-modal>
<app-modal [isOpen]="deleteStockModalOpen()" title="Eliminar material" maxWidth="max-w-md" (close)="closeDeleteStockModal()"><div body class="text-sm text-slate-600">¿Seguro que deseas eliminar <strong>{{ deletingStock()?.material?.name }}</strong> de <strong>{{ deletingStock()?.group?.name }}</strong>? Las existencias del mismo material en otras áreas no se modificarán.</div><div footer><button type="button" class="btn-outline" [disabled]="saving()" (click)="closeDeleteStockModal()">Cancelar</button><button type="button" class="btn-danger" [disabled]="saving()" (click)="deleteStock()"><lucide-icon name="trash-2" [size]="14"></lucide-icon> Eliminar</button></div></app-modal>
<app-modal [isOpen]="stockModalOpen()" [title]="editingStock() ? 'Editar cantidad' : 'Registrar existencias'" maxWidth="max-w-md" (close)="closeStockModal()"><div body class="space-y-4"><div><label class="block text-xs font-semibold mb-1">Área / Zona *</label><select [(ngModel)]="stockForm.groupId" [disabled]="!!editingStock()" class="select-smp"><option [ngValue]="null" disabled>Selecciona un área</option><option *ngFor="let group of groups()" [ngValue]="group.id">{{ group.name }}</option></select></div><div *ngIf="!editingStock()"><label class="block text-xs font-semibold mb-1">Material *</label><select [(ngModel)]="stockForm.materialId" class="select-smp"><option [ngValue]="null" disabled>Selecciona un material existente</option><option *ngFor="let material of materials()" [ngValue]="material.id">{{ material.name }}</option></select><div class="flex items-center gap-2 my-3 text-xs text-slate-400"><span class="flex-1 border-t"></span>o crear uno nuevo<span class="flex-1 border-t"></span></div><input [(ngModel)]="newMaterialName" class="input-smp" placeholder="Ej: Cargadores" /></div><div *ngIf="editingStock()"><label class="block text-xs font-semibold mb-1">Material</label><p class="input-smp bg-slate-50">{{ editingStock()?.material?.name }}</p></div><div><label class="block text-xs font-semibold mb-1">{{ editingStock() ? 'Cantidad total en esta área' : 'Cantidad a añadir' }} *</label><input type="number" min="0" [(ngModel)]="stockForm.quantity" class="input-smp" /></div></div><div footer><button class="btn-outline" (click)="closeStockModal()">Cancelar</button><button class="btn-primary" [disabled]="saving() || !stockForm.groupId || (!stockForm.materialId && !newMaterialName) || stockForm.quantity < 0" (click)="saveStock()">Guardar</button></div></app-modal></div>` })
export class CategoriesComponent implements OnInit {
  groups = signal<Group[]>([]); materials = signal<Material[]>([]); stocks = signal<AreaMaterialStock[]>([]); computers = signal<Computer[]>([]); selectedGroupId = signal<number | null>(null); saving = signal(false); areaModalOpen = signal(false); deleteAreaModalOpen = signal(false); deleteStockModalOpen = signal(false); stockModalOpen = signal(false); editingArea = signal<Group | null>(null); editingStock = signal<AreaMaterialStock | null>(null); deletingStock = signal<AreaMaterialStock | null>(null); areaName = ''; areaDescription = ''; newMaterialName = ''; stockPage = 1; readonly pageSize = 10; stockForm = { groupId: null as number | null, materialId: null as number | null, quantity: 1 };
  rows = computed<AreaInventoryRow[]>(() => {
    const materialRows = this.stocks().map((stock) => ({ key: `stock-${stock.id}`, groupId: stock.groupId, name: stock.material?.name || 'Material', groupName: stock.group?.name || 'Área / zona', quantity: stock.quantity, stock }));
    const computerRows = this.groups().map((group) => ({ key: `computers-${group.id}`, groupId: group.id, name: 'Laptops', groupName: group.name, quantity: this.computers().filter((computer) => computer.areaId === group.id).length })).filter((row) => row.quantity > 0);
    return [...materialRows, ...computerRows];
  });
  filteredRows = computed(() => this.rows().filter((row) => this.selectedGroupId() === null || row.groupId === this.selectedGroupId()));
  constructor(private api: ApiService, private toast: ToastService, private route: ActivatedRoute) {}
  ngOnInit() { this.route.queryParamMap.subscribe((params) => { const id = Number(params.get('groupId')); this.selectGroup(id > 0 ? id : null); }); this.load(); }
  load() { this.api.get<Group[]>('/groups').subscribe({ next: g => this.groups.set(g) }); this.api.get<Material[]>('/materials').subscribe({ next: m => this.materials.set(m) }); this.api.get<Computer[]>('/computers').subscribe({ next: c => { this.computers.set(c); this.stockPage = Math.min(this.stockPage, this.stockPageCount()); }, error: () => this.toast.error('No se pudieron cargar las laptops.') }); this.api.get<AreaMaterialStock[]>('/materials/stocks').subscribe({ next: s => { this.stocks.set(s); this.stockPage = Math.min(this.stockPage, this.stockPageCount()); }, error: () => this.toast.error('No se pudieron cargar los materiales.') }); }
  selectGroup(id: number | null) { this.selectedGroupId.set(id); this.stockPage = 1; }
  stockPageCount() { return Math.max(1, Math.ceil(this.filteredRows().length / this.pageSize)); }
  pagedRows() { return this.filteredRows().slice((this.stockPage - 1) * this.pageSize, this.stockPage * this.pageSize); }
  openAreaModal(area?: Group) { this.editingArea.set(area || null); this.areaName = area?.name || ''; this.areaDescription = area?.description || ''; this.areaModalOpen.set(true); }
  saveArea() { const name = this.areaName.trim(); if (!name) return; this.saving.set(true); const area = this.editingArea(); const payload = { name, description: this.areaDescription.trim() }; const request = area ? this.api.put(`/groups/${area.id}`, payload) : this.api.post('/groups', payload); request.subscribe({ next: () => { this.toast.success(area ? 'Área actualizada.' : 'Área creada.'); this.saving.set(false); this.areaModalOpen.set(false); this.load(); }, error: e => { this.toast.error(e?.error?.message || 'No se pudo guardar el área.'); this.saving.set(false); } }); }
  deleteArea() { const area = this.editingArea(); if (!area || this.saving()) return; this.saving.set(true); this.api.delete(`/groups/${area.id}`).subscribe({ next: () => { this.toast.success('Área eliminada.'); this.saving.set(false); this.deleteAreaModalOpen.set(false); this.areaModalOpen.set(false); if (this.selectedGroupId() === area.id) this.selectGroup(null); this.load(); }, error: e => { this.toast.error(e?.error?.message || 'No se pudo eliminar el área.'); this.saving.set(false); this.deleteAreaModalOpen.set(false); } }); }
  confirmDeleteStock(stock: AreaMaterialStock) { this.deletingStock.set(stock); this.deleteStockModalOpen.set(true); }
  closeDeleteStockModal() { if (this.saving()) return; this.deleteStockModalOpen.set(false); this.deletingStock.set(null); }
  deleteStock() { const stock = this.deletingStock(); if (!stock || this.saving()) return; this.saving.set(true); this.api.delete(`/materials/stocks/${stock.id}`).subscribe({ next: () => { this.saving.set(false); this.closeDeleteStockModal(); this.toast.success('Material eliminado del área.'); this.load(); }, error: e => { this.toast.error(e?.error?.message || 'No se pudo eliminar el material.'); this.saving.set(false); } }); }
  openStockModal(stock?: AreaMaterialStock) { this.editingStock.set(stock || null); this.newMaterialName = ''; this.stockForm = stock ? { groupId: stock.groupId, materialId: stock.materialId, quantity: stock.quantity } : { groupId: this.selectedGroupId() || this.groups()[0]?.id || null, materialId: null, quantity: 1 }; this.stockModalOpen.set(true); }
  closeStockModal() { this.stockModalOpen.set(false); this.editingStock.set(null); }
  saveStock() { const edit = this.editingStock(); this.saving.set(true); if (edit) { this.api.put(`/materials/stocks/${edit.id}`, { quantity: Number(this.stockForm.quantity) }).subscribe({ next: () => this.finish('Cantidad actualizada.'), error: e => this.fail(e) }); return; } if (this.newMaterialName.trim()) { this.api.post<Material>('/materials', { name: this.newMaterialName }).subscribe({ next: m => { this.stockForm.materialId = m.id; this.addStock(); }, error: e => this.fail(e) }); } else this.addStock(); }
  private addStock() { this.api.post('/materials/stocks', { groupId: this.stockForm.groupId, materialId: this.stockForm.materialId, quantity: Number(this.stockForm.quantity) }).subscribe({ next: () => this.finish('Existencias registradas.'), error: e => this.fail(e) }); }
  private finish(message: string) { this.toast.success(message); this.saving.set(false); this.closeStockModal(); this.load(); }
  private fail(error: any) { this.toast.error(error?.error?.message || 'No se pudo guardar.'); this.saving.set(false); }
}
